// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCIR5_zud0A91eSwOAz6_ewDABrbN-O8',
    appId: '1:146074968563:web:ab7fbb190558a381c57286',
    messagingSenderId: '146074968563',
    projectId: 'flutter-test-f68bd',
    authDomain: 'flutter-test-f68bd.firebaseapp.com',
    storageBucket: 'flutter-test-f68bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr_cX2O6szIT9p1njtFpe8A6Tkorc01w',
    appId: '1:146074968563:android:8097c1fb91345fe2c57286',
    messagingSenderId: '146074968563',
    projectId: 'flutter-test-f68bd',
    storageBucket: 'flutter-test-f68bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1i-V6fM3jseCLxF7jzCPctDEaobDQ53w',
    appId: '1:146074968563:ios:87e54a67885ee795c57286',
    messagingSenderId: '146074968563',
    projectId: 'flutter-test-f68bd',
    storageBucket: 'flutter-test-f68bd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1i-V6fM3jseCLxF7jzCPctDEaobDQ53w',
    appId: '1:146074968563:ios:87e54a67885ee795c57286',
    messagingSenderId: '146074968563',
    projectId: 'flutter-test-f68bd',
    storageBucket: 'flutter-test-f68bd.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
